version: "3.8"

services:
  sqlServer:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlServer
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "MyStrongPass123"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
